### ISSUE TITLE
[ISSUE] - Source

### ISSUE THREAD

**Issue by xRuffKez** [SystemJargon/nrd-lists#1]
### Subject of the issue
Source is dead

### Your observation/s and environment:

* Does a domain or URL not load/does load because of it being on an allowlist/blocklist?
* What web browser and version are you using
* Confirmed it is not upstream DNS not-blocking/blocking said URL/Domain or other such issue.
* Is this an issue related to this repository?
* Screenshots/source files are nice to include.

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by SystemJargon** [comment]
NRD lists look like they are compiling fine.

Currently i see the GH workflow running without errors and lists show updates, i.e. "Update filter list at 20240415".

**Comment by xRuffKez** [comment]
Unfurtunately nrd-list.com is dead since mid february and not updated. The other source only contains 50k domains? I mean my nrd list is around 2,9mil per 30 days

**Comment by SystemJargon** [comment]
Sorry you are correct for the sake of the domain nrd-list.com

Please allow me some time to fetch some other sources and feeds and re-compile to this repo.

**Comment by SystemJargon** [comment]
This will be worked on in Issue #3
